### PR TITLE
Enable build on MinGW/MSYS2

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by orgads** [comment]
Ping? Is this project maintained?

**Comment by imankulov** [comment]
Hey @orgads, stellar work here 😍 

You're right, I abandoned the project, but I also didn't do anything with your PR because I wasn't sure if your work is ready for the review and the merge. Now I checked it and it looks good to merge.

Can you please do one last change here: update the AUTHORS file and add yourself to the list of contributors. Please ping me when you're done so that I can merge it in. Thanks!

**Comment by orgads** [comment]
Done

**Comment by imankulov** [comment]
Thanks a lot, @orgads! Your contribution is appreciated. 

Meanwhile, I will clarify in the README that the project is not under active development and is looking for maintainers.

**Comment by orgads** [comment]
I'm willing to maintain it. Not many issues and not many users anyway :)

**Comment by imankulov** [comment]
Thanks, @orgads. I invited you as a collaborator.

**Pull request merged**
